config/routes.rb
Rails.application.routes.draw do

  get 'admin/users/:id/confirm_destroy', :to => 'admin/users#confirm_destroy', :as => :admin_confirm_destroy

  devise_for :users, :skip => :registrations

  authenticated :user do
    root 'admin/dashboard#index', :as => :dashboard
  end

  namespace :admin do
    resources :users
    resources :notes
  end

  # You can have the root of your site routed with "root"
  # just remember to delete public/index.html.
  root 'welcome#index'

end

app/models/note.rb
class Note < ActiveRecord::Base
  belongs_to :visitor
  belongs_to :author
  belongs_to :publication

  accepts_nested_attributes_for :visitor, :author, :publication, update_only: true

  validates :publication, :presence => true

  def set_as_deleted
    update_attribute :is_deleted, true
  end
end

app/controllers/admin/notes_controller.rb
class Admin::NotesController < Admin::AdminController
  before_action :set_note, only: [:show, :edit, :update, :destroy]

  # GET /notes
  # GET /notes.json
  def index
    @notes = Note.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @notes }
    end
  end

  # GET /notes/1
  # GET /notes/1.json
  def show
    @note = Note.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @note }
    end
  end

  # GET /notes/new
  # GET /notes/new.json
  def new
    @note = Note.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @note }
    end
  end

  # GET /notes/1/edit
  def edit
    @note = Note.find(params[:id])
  end

  # POST /notes
  # POST /notes.json
  def create
    @note = Note.new(note_params)

    respond_to do |format|
      if @note.save
        format.html { redirect_to dashboard_path, notice: 'Note was successfully created.' }
        format.json { render json: @note, status: :created, location: @note }
      else
        format.html { redirect_to dashboard_path, notice: 'Note was not created.' }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /notes/1
  # PUT /notes/1.json
  def update
    @note = Note.find(params[:id])

    respond_to do |format|
      if @note.update_attributes(note_params) #&& @note.update_attributes(params[:visitor_attributes]) || @note.update_attributes(params[:author_attributes]) || @note.update_attributes(params[:publication_attributes])
        format.html { redirect_to dashboard_path, notice: 'Note was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { redirect_to dashboard_path, notice: 'Note was not updated.' }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notes/1
  # DELETE /notes/1.json
  def destroy
    @note = Note.find(params[:id])
    @note.set_as_deleted

    respond_to do |format|
      format.html { redirect_to dashboard_url, notice: 'Note was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_note
    @note = Note.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def note_params
    params.require(:note).permit! #.permit(visitor_attributes: [:name], author_attributes: [:name], publication_attributes: [:title, :description])
  end
end

app/helpers/admin/notes_helper.rb
module Admin::NotesHelper

  def link_to_note_show(record)
    link_to image_tag('notebook.png'), admin_note_path(record)
  end

  def link_to_note_edit(record)
    link_to image_tag('notebook_edit.png'), edit_admin_note_path(record)
  end

  def link_to_note_destroy(record)
    link_to image_tag('notebook_delete.png'),
            admin_note_path(record), :method => :delete, :data => {confirm: t(:note_confirm_destroy_text)}
  end
end

app/views/admin/notes/_form.html.haml
= form_for ([:admin, @note]) do |f|
  - if @note.errors.any?
  - @note.errors.count > 1 ? text = t(:errors) : text = t(:error)
    #error_explanation
      %h2= @note.errors.count.to_s + text + t(:note_not_saved_text)
      %ul
        - @note.errors.full_messages.each do |msg|
          %li= msg

  %table.center
    %tr
      = f.fields_for :visitor_attributes do |v_fields|
        - controller_name == 'dashboard' ? value = nil : value = @note.visitor.name
        %td= v_fields.label t(:note_visitor) + ' *'
        %td= v_fields.text_field :name, value: value, autofocus: true, required: 'required', data: {message: t(:note_visitor) + ' ' + t(:required)}
    %tr
      = f.fields_for :author_attributes do |a_fields|
        - controller_name == 'dashboard' ? value = nil : value = @note.author.name
        %td= a_fields.label t :note_author
        %td= a_fields.text_field :name, value: value
    = f.fields_for :publication_attributes do |p_fields|
      - controller_name == 'dashboard' ? title = nil : title = @note.publication.title
      - controller_name == 'dashboard' ? description = nil : description = @note.publication.description
      %tr
        %td= p_fields.label t :note_publication
        %td= p_fields.text_field :title, value: title
      %tr
        %td= p_fields.label t :note_note
        %td= p_fields.text_field :description, value: description
      %tr
        %td
        %td= f.submit t :save_title

= hidden_field_tag 'visitors', nil, data: { visitors: @visitors }
= hidden_field_tag 'authors', nil, data: { authors: @authors }
= hidden_field_tag 'titles', nil, data: { titles: @titles }
= hidden_field_tag 'descriptions', nil, data: { descriptions: @descriptions }

app/views/admin/notes/edit.html.haml
= title t :note_title_edit

= render 'form'

= link_to t(:note_title_show), admin_note_path(@note)
\|
= link_to t(:notes), dashboard_path

app/views/admin/notes/index.html.haml
= title t :notes

%table.wide
  %tr
    %th
    %th
    %th
    %th
    %th
    %th
    %th

  - @notes.each do |note|
    %tr.row{class: cycle('odd', 'even')}
      %td= note.created_at.strftime('%F %R')
      %td= note.visitor.name
      %td= note.author.name
      %td= truncate note.publication.title
      %td.column= link_to_note_show(note)
      %td.column= link_to_note_destroy(note)

app/views/admin/notes/new.html.haml
= title t :note_title_new

= render 'form'

= link_to t(:notes), admin_notes_path

app/views/admin/notes/show.html.haml
= title t :note_title_show

%p
  .label= t :note_visitor
  = @note.visitor.name
%p
  .label= t :note_author
  = @note.author.name
%p
  .label= t :note_publication
  = @note.publication.title
  = @note.publication.description

= link_to t(:notes), dashboard_path