config/routes.rb
Rails.application.routes.draw do

  get 'admin/users/:id/confirm_destroy', :to => 'admin/users#confirm_destroy', :as => :admin_confirm_destroy

  devise_for :users, :skip => :registrations

  authenticated :user do
    root 'admin/dashboard#index', :as => :dashboard
  end

  namespace :admin do
    resources :users
    resources :notes
  end

  # You can have the root of your site routed with "root"
  # just remember to delete public/index.html.
  root 'welcome#index'

end

app/models/user.rb
class User < ActiveRecord::Base
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


  after_create :create_role

  private
  def create_role
    add_role :admin
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::AdminController

  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to admin_user_path(@user), notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: 'new' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(user_params)
        format.html { redirect_to admin_user_path(@user), notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to admin_users_url, notice: 'User was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  def confirm_destroy
    @user = User.find(params[:id])

    respond_to do |format|
      format.html { render :action => 'destroy' }
      format.json { render json: @user }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def user_params
    params.require(:user).permit!
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper

  def link_to_admin_show(record)
    link_to image_tag('business_user_info.png'),
            :controller => 'users', :action => 'show', :id => record.id
  end

  def link_to_admin_edit(record)
    link_to image_tag('business_user_edit.png'),
            :controller => 'users', :action => 'edit', :id => record.id
  end

  def link_to_admin_destroy(record)
    link_to image_tag('business_user_delete.png'),
            :controller => 'users', :action => 'confirm_destroy', :id => record.id
  end
end

app/views/admin/users/_form.html.haml
= form_for ([:admin, @user]) do |f|
  - if @user.errors.any?
    #error_explanation
      %h2= "#{pluralize(@user.errors.count, 'error')} prohibited this playlist from being saved:"
      %ul
        - @user.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label t :user_label_name
    = f.text_field :name
  .field
    = f.label t :user_label_email
    = f.email_field :email
  .field
    = f.label t :label_password
    = f.password_field :password
  .actions
    = f.submit t :save_title

app/views/admin/users/destroy.html.haml
= title t :user_title_destroy

= form_for(([:admin, @user]), :url => admin_user_path(@user), :html => {:method => :delete}) do |f|
  = image_tag 'warning.png', title: t(:user_title_destroy)
  %span #{t :user_confirm_destroy_text}&nbsp;#{@user.name}&#063;

  %br
    = f.submit t(:destroy_title)
    = link_to t(:cancel_title), admin_users_url

app/views/admin/users/edit.html.haml
= title t :user_title_edit

= render 'form'

= link_to t(:user_title_show), admin_user_path(@user)
\|
= link_to t(:users), admin_users_url

app/views/admin/users/index.html.haml
= title t :users

%table.wide
  %tr
    %th
    %th
  - @users.each do |user|
    %tr.row{class: cycle('odd', 'even')}
      %td= link_to user.name, admin_user_path(user)
      %td= mail_to(user.email, user.email, title: user.email)
      %td.column= link_to_admin_show(user)
      %td.column= link_to_admin_edit(user)
      %td.column= link_to_admin_destroy(user)

= link_to t(:user_title_new), new_admin_user_path

app/views/admin/users/new.html.haml
= title t :user_title_new

= render 'form'

= link_to t(:users), admin_users_url

app/views/admin/users/show.html.haml
= title t :user_title_show

%p
  = t :user_label_name
  = @user.name
%p
  = t :user_label_email
  = mail_to(@user.email, @user.email, title: @user.email)

= link_to t(:users), admin_users_url

= link_to t(:user_title_edit), edit_admin_user_path(@user)